/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmistoreclient.ui.tabs.items;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import rmistore.commons.exceptions.Rejected;
import rmistore.commons.interfaces.Item;
import rmistore.commons.interfaces.Transaction;
import rmistoreclient.helper.RMIStoreClientHelper;

/**
 *
 * @author davidsoendoro
 */
public class RMIStoreClientTransactionItem extends javax.swing.JPanel {

    private Transaction transaction;
    
    /**
     * Creates new form RMIStoreClientBuyItem
     */
    public RMIStoreClientTransactionItem() {
        initComponents();
    }
    
    public RMIStoreClientTransactionItem(Transaction transaction) {
        this.transaction = transaction;
        
        initComponents();
        
        jLabelName.setText(transaction.getItemName());
        jLabelPrice.setText("$" + transaction.getPrice());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 0));

        jLabelName.setText("Name");
        add(jLabelName);

        jLabelPrice.setText("$0.00");
        add(jLabelPrice);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPrice;
    // End of variables declaration//GEN-END:variables
}
